version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web: &web_base
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpack-dev-server:
    <<: *web_base
    command: bin/webpack-dev-server
    ports:
      - "3035:3035"
volumes:
  bundle:
  node_modules:
